name: build

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@b184ff86a3c926240f1b6db41764c83a01c02eef # v8 tag has not been updated
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build Android production apk
        if: startsWith(github.ref, 'refs/tags/')
        run: eas build -p android --profile production --non-interactive

      - name: 🚀 Build Android preview apk
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: eas build -p android --profile preview --non-interactive

      - name: 📥 Download APK from EAS
        run: |
          APK_URL=$(eas build:list --platform android --status finished --limit 1 --json --non-interactive | jq -r '.[0].artifacts.buildUrl')
          curl -L -o ${{ github.workspace }}/medium_unlocker_${{ github.ref_name }}.apk "$APK_URL"

      - name: 🚀 Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: medium_unlocker.apk
          path: ${{ github.workspace }}/medium_unlocker_${{ github.ref_name }}.apk

      - name: 🚀 Upload APK to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/medium_unlocker_${{ github.ref_name }}.apk
